on:
  push:
    branches:
      - test

jobs:
  docker-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t my-java-app:latest .

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Scan Docker Image
        run: snyk container test my-java-app:latest --file=Dockerfile

      - name: Monitor Docker Image
        run: snyk container monitor my-java-app:latest --file=Dockerfile
